services:
  apache:
    build: ./apache
    ports:
      - '8080:80'
    volumes:
      - ./apache:/usr/local/apache2/htdocs/
  php:
    image: php:7.4-fpm
    volumes:
      - ./php/:/var/www/html/
    ports:
      - '8100:80'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: sheep
    ports: 
      - '3306:80'
    volumes:  
      - ./db:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql

volumes:
  db-volume: