services:
  web:
    image: httpd:2.4
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: sheep
    ports: 
      - '3306:80'
    volumes:  
      - ./db:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'

volumes:
  db-volume: